//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DialogElements {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DialogElements() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.DialogElements", typeof(DialogElements).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string General_ButtonApplyName {
            get {
                return ResourceManager.GetString("General_ButtonApplyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string General_ButtonCancelName {
            get {
                return ResourceManager.GetString("General_ButtonCancelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string General_ButtonOkName {
            get {
                return ResourceManager.GetString("General_ButtonOkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; Apply.
        /// </summary>
        public static string General_ButtonSaveApplyName {
            get {
                return ResourceManager.GetString("General_ButtonSaveApplyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string General_Search {
            get {
                return ResourceManager.GetString("General_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Template Ceiling.
        /// </summary>
        public static string RoomStudy_CeilingTemplateSelector {
            get {
                return ResourceManager.GetString("RoomStudy_CeilingTemplateSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Template Elevation.
        /// </summary>
        public static string RoomStudy_ElevationTemplateSelector {
            get {
                return ResourceManager.GetString("RoomStudy_ElevationTemplateSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elevation Type.
        /// </summary>
        public static string RoomStudy_ElevationTypeSelector {
            get {
                return ResourceManager.GetString("RoomStudy_ElevationTypeSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Template Floor.
        /// </summary>
        public static string RoomStudy_FloorTemplateSelector {
            get {
                return ResourceManager.GetString("RoomStudy_FloorTemplateSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naming.
        /// </summary>
        public static string RoomStudy_NamingMenuHeader {
            get {
                return ResourceManager.GetString("RoomStudy_NamingMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titleblock.
        /// </summary>
        public static string RoomStudy_TitleBlockSelector {
            get {
                return ResourceManager.GetString("RoomStudy_TitleBlockSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types.
        /// </summary>
        public static string RoomStudy_TypeMenuHeader {
            get {
                return ResourceManager.GetString("RoomStudy_TypeMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built In Parameters.
        /// </summary>
        public static string SelectSimilar_BIPHeader {
            get {
                return ResourceManager.GetString("SelectSimilar_BIPHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string SelectSimilar_CategoriesHeader {
            get {
                return ResourceManager.GetString("SelectSimilar_CategoriesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Parameters.
        /// </summary>
        public static string SelectSimilar_CustomParametersHeader {
            get {
                return ResourceManager.GetString("SelectSimilar_CustomParametersHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Parameters.
        /// </summary>
        public static string SelectSimilar_GeneralParametersHeader {
            get {
                return ResourceManager.GetString("SelectSimilar_GeneralParametersHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No instance or type of this category exists in this document.
        /// </summary>
        public static string SelectSimilar_Message {
            get {
                return ResourceManager.GetString("SelectSimilar_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search categories....
        /// </summary>
        public static string SelectSimilar_PlaceholderCategories {
            get {
                return ResourceManager.GetString("SelectSimilar_PlaceholderCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search parameters....
        /// </summary>
        public static string SelectSimilar_PlaceholderParameters {
            get {
                return ResourceManager.GetString("SelectSimilar_PlaceholderParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppress main dialog.
        /// </summary>
        public static string SelectSimilar_Suppress {
            get {
                return ResourceManager.GetString("SelectSimilar_Suppress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Similar.
        /// </summary>
        public static string SelectSimilar_VisibleInView {
            get {
                return ResourceManager.GetString("SelectSimilar_VisibleInView", resourceCulture);
            }
        }
    }
}
